[WIP] v2
calyptia/go-fluentbit-config pull request #42
Opened 2022-10-20 02:40 UTC by nicolasparada

2022-11-07 18:04 UTC, nicolasparada commented on testdata/multiline-value.yaml
> +        multline: '"FOO\nBAR"'
I would like if this were translated into:
```suggestion
        multline: -|
            FOO
            BAR
```

2022-11-07 18:06 UTC, nicolasparada commented on testdata/multiline-value.yaml
> +        multiline: '"FOO\nBAR"'
I'll look into it.

2022-11-09 13:23 UTC, niedbalski commented on testdata/multiline-value.yaml
> +        multiline: '"FOO\nBAR"'
will you fix this @nicolasparada

2022-11-09 13:27 UTC, nicolasparada commented on testdata/multiline-value.yaml
> +        multiline: '"FOO\nBAR"'
Yup

2022-11-09 13:32 UTC, niedbalski requested changes
Great work.

Looks generally good. I think the parsing schema for json might be a bit fragile. 

1. Did you remove the schema validator entirely from this parser?
2. Any chance you can re-instate the original tests? I am particularly interested
into booleans, multi-field, urls (with schema + port + uri) and the multiple-files ones.

2022-11-09 16:16 UTC, nicolasparada commented on testdata/multiline-value.yaml
> +        multiline: '"FOO\nBAR"'
Done.

2022-11-09 16:17 UTC, nicolasparada commented
1. I'm bringing the validator back.
2. I have already a good suite of tests, but sure I can add those :)

2022-11-09 19:23 UTC, merged