add equal method
calyptia/go-fluentbit-config pull request #53
Opened 2023-01-09 16:04 UTC by nicolasparada

Closes https://github.com/calyptia/go-fluentbit-config/issues/52

2023-01-09 22:02 UTC, pwhelan requested changes

2023-01-09 22:02 UTC, pwhelan commented on config.go
> +	"golang.org/x/exp/maps"
I'm a bit concerned about using `exp` packages. I was unable to gloss anything about their status. The functionality they provide can probably just be re-implemented quickly if needed. Add some tests that actually use the functionality explicitly, ie:

- Equality where the map is defined in a different order
- Slices in different order

Just to make sure we catch a few of the corner cases they are meant to handle and I think that should be enough to cover the risk there.

2023-01-10 11:12 UTC, nicolasparada commented on config.go
> +	"golang.org/x/exp/maps"
I added tests for the slices.
The map... well the thing is that config should not have a map with more than one key. This map is single key.

Array -> single key map -> properties.

Otherwise you cannot define the same plugin (input, parser, filter or output) multiple times.

2023-01-10 14:51 UTC, pwhelan commented on config.go
> +	"golang.org/x/exp/maps"
I was trying to think of a case where we need to compare maps directly but none occur to me for now.

2023-01-10 14:51 UTC, pwhelan approved these changes

2023-01-10 15:00 UTC, merged