v2
calyptia/go-fluentbit-config pull request #57
Opened 2023-03-17 18:04 UTC by nicolasparada

Removing the single item array, and place properties directly, aka:

From:

```yaml
pipeline:
  inputs:
    - dummy
      name: dummy
```

To:

```yaml
pipeline:
  inputs:
    - name: dummy
```

This is to align with fluent-bit new YAML format.

Also improved how IDs work by placing them directly on the struct instead of computing them each time.

Also added service port detection. This is so we can create the service ports on kubernetes. This is something we currently do on Cloud but it's not complete and some plugins don't generate a service port.

2023-03-18 02:11 UTC, nicolasparada commented
CI takes around 10 seconds. Nice :D

2023-03-20 14:20 UTC, patrick-stephens requested changes

2023-03-20 14:20 UTC, patrick-stephens commented on .github/workflows/ci.yaml
> +        run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
Let's set a version as it will not be reproducible

2023-03-30 08:36 UTC, patrick-stephens commented
@jasmingacic let's get this merged if we can.

2023-03-30 10:03 UTC, jasmingacic approved these changes
Changes look good. 

Merge it whenever you want

2023-03-30 11:06 UTC, merged