processors: add support for the new processors feature.
calyptia/go-fluentbit-config pull request #61
Opened 2023-05-18 16:31 UTC by pwhelan

# Summary

Add support for the new processors feature in the upcoming fluent-bit release.

# Description

Add support for parsing and validating [processors](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml/configuration-file#config_processors).

2023-05-19 07:46 UTC, niedbalski requested changes
Overall looks good, I think we need some refactoring (I pointed in the code) for better readability of the code.

2023-05-19 07:47 UTC, niedbalski commented on validator.go
> +func validateProcessors(processors any) error {
I suggest some refactoring to better readability of this code.

```go
func validateProcessors(processors any) error {
    procMap, ok := processors.(map[string]interface{})
    if !ok {
        return fmt.Errorf("not a list of processors")
    }

    for key, sections := range procMap {
        sectionMaps, ok := sections.([]interface{})
        if !ok {
            return fmt.Errorf("not a list of processors")
        }

        switch key {
        case "logs", "metrics", "traces":
            if err := validateSectionMaps(sectionMaps); err != nil {
                return err
            }
        default:
            return fmt.Errorf("unknown processor type: %s", key)
        }
    }

    return nil
}

func validateSectionMaps(sectionMaps []interface{}) error {
    for _, section := range sectionMaps {
        props := property.Properties{}
        for key, val := range section.(map[string]interface{}) {
            props.Set(key, val)
        }
        if err := ValidateSection(SectionKindFilter, props); err != nil {
            return err
        }
    }

    return nil
}

```

2023-05-19 13:52 UTC, pwhelan commented on validator.go
> +func validateProcessors(processors any) error {
```go
        switch key {
        case "logs", "metrics", "traces":
```

Did not know that was possible.

2023-05-21 21:50 UTC, niedbalski approved these changes

2023-05-22 08:07 UTC, merged